baseURL = "https://staging.port-zero.com/"
theme = "portzero"
[outputs]
  home = ["HTML"]
  page = ["HTML"]


[languages]
  [languages.en]
    title = "Port Zero"
    languageName = "en"
    weight = 1
    [languages.en.params]
      description = "IT-Security and software development"
  [languages.de]
    title = "Port Zero"
    languageName = "de"
    weight = 2
    [languages.de.params]
      description = "IT-Sicherheit und Software Entwicklung auf höchstem Niveau"

DefaultContentLanguage = "de"

[[menu.main]]
  name = "GitHub"
  weight = 20
  parent = "References"
  identifier = "github"
  url = "https://github.com/port-zero"
[[menu.main]]
  name = "LinkedIn"
  parent = "References"
  weight = 30
  identifier = "linkedin"
  url = "https://www.linkedin.com/company/5061707/"


[[languages.de.menu.social]]
  name = "GitHub"
  weight = -100
  parent = "Referenzen"
  identifier = "github"
  url = "https://github.com/port-zero"
[[languages.de.menu.social]]
  name = "LinkedIn"
  parent = "Referenzen"
  weight = -90
  identifier = "linkedin"
  url = "https://www.linkedin.com/company/5061707/"
