baseURL = "http://staging.port-zero.com/"
languageCode = "en-us"
title = "Port Zero"
theme = "portzero"
[params]
  description = "Excellent Software Solutions"
  licence = "[Some Rights Reserved](http://creativecommons.org/licenses/by-sa/4.0/)."
[outputs]
  home = ["HTML"]
  page = ["HTML"]


[[menu.main]]
  name = "Unternehmen"
  weight = -100
  identifier = "company"
  url = "/"
[[menu.main]]
  name = "Team"
  weight = -90
  identifier = "team"
  url = "/team/"
[[menu.main]]
  name = "Referenzen"
  weight = -80
  identifier = "references"
  url = "/references/"
[[menu.main]]
  name = "Kontakt"
  weight = -70
  identifier = "contact"
  url = "mailto:contact@port-zero.com"
[[menu.main]]
  name = "Impressum"
  weight = -60
  identifier = "imprint"
  url = "/imprint/"








[[menu.secondary]]
  name = "GitHub"
  weight = -100
  identifier = "github"
  url = "https://github.com/port-zero"
[[menu.secondary]]
  name = "LinkedIn"
  weight = -90
  identifier = "linkedin"
  url = "https://www.linkedin.com/company/5061707/"

