baseURL = "https://staging.port-zero.com/"
theme = "portzero"
[outputs]
  home = ["HTML"]
  page = ["HTML"]


[languages]
  [languages.en]
    title = "Port Zero"
    languageName = "Deutsch"
    weight = 1
    [languages.en.params]
      description = "IT-Security and software development"
  [languages.de]
    title = "Port Zero"
    languageName = "English"
    weight = 2
    [languages.de.params]
      description = "IT-Sicherheit und Software Entwicklung auf höchstem Niveau"

DefaultContentLanguage = "Deutsch"

[[menu.main]]
  name = "GitHub"
  weight = 30
  parent = "Contact"
  identifier = "github"
  url = "https://github.com/port-zero"
[[menu.main]]
  name = "LinkedIn"
  parent = "Contact"
  weight = 40
  identifier = "linkedin"
  url = "https://www.linkedin.com/company/5061707/"


[[languages.de.menu.social]]
  name = "GitHub"
  weight = 30 
  parent = "Kontakt"
  identifier = "github"
  url = "https://github.com/port-zero"
[[languages.de.menu.social]]
  name = "LinkedIn"
  parent = "Kontakt"
  weight = 40 
  identifier = "linkedin"
  url = "https://www.linkedin.com/company/5061707/"
