baseURL = "https://port-zero.com/"
theme = "portzero"
[outputs]
  home = ["HTML"]
  page = ["HTML"]


[languages]
  [languages.en]
    title = "Port Zero"
	languageName = "English"
    weight = 1
    [languages.en.params]
      description = "IT-Security and software development"
  [languages.de]
    title = "Port Zero"
	languageName = "Deutsch"
    weight = 2
    [languages.de.params]
      description = "IT-Sicherheit und Software Entwicklung auf höchstem Niveau"

DefaultContentLanguage = "de"


[[menu.main]]
  name = "Company"
  weight = -100
  identifier = "company"
  url = "/"
[[menu.main]]
  name = "Team"
  weight = -90
  identifier = "team"
  url = "/team/"
[[menu.main]]
  name = "References"
  weight = -80
  identifier = "references"
  url = "/references/"
[[menu.main]]
  name = "GDPR-Compliance"
  weight = -75
  identifier = "gdpr"
  url = "/gdpr/"
[[menu.main]]
  name = "Contact"
  weight = -70
  identifier = "contact"
  url = "/contact/"
[[menu.main]]
  name = "Privacy Policy"
  weight = -65
  identifier = "privacypolicy"
  url = "/privacypolicy/"
[[menu.main]]
  name = "Imprint"
  weight = -60
  identifier = "imprint"
  url = "/imprint/"



[[languages.de.menu.main]]
  name = "Unternehmen"
  weight = -100
  identifier = "company"
  url = "/de/"
[[languages.de.menu.main]]
  name = "Team"
  weight = -90
  identifier = "team"
  url = "/de/team/"
[[languages.de.menu.main]]
  name = "Referenzen"
  weight = -80
  identifier = "references"
  url = "/de/references/"
[[languages.de.menu.main]]
  name = "DSGVO-Compliance"
  weight = -75
  identifier = "gdpr"
  url = "/de/gdpr/"
[[languages.de.menu.main]]
  name = "Kontakt"
  weight = -70
  identifier = "contact"
  url = "/de/contact/"
[[languages.de.menu.main]]
  name = "Datenschutzerklärung"
  weight = -65
  identifier = "privacypolicy"
  url = "/de/privacypolicy/"
[[languages.de.menu.main]]
  name = "Impressum"
  weight = -60
  identifier = "imprint"
  url = "/de/imprint/"




[[menu.secondary]]
  name = "GitHub"
  weight = -100
  identifier = "github"
  url = "https://github.com/port-zero"
[[menu.secondary]]
  name = "LinkedIn"
  weight = -90
  identifier = "linkedin"
  url = "https://www.linkedin.com/company/5061707/"
[[menu.secondary]]
  name = "Twitter"
  weight = -80
  identifier = "twitter"
  url = "https://twitter.com/port_zer0"


[[languages.de.menu.secondary]]
  name = "GitHub"
  weight = -100
  identifier = "github"
  url = "https://github.com/port-zero"
[[languages.de.menu.secondary]]
  name = "LinkedIn"
  weight = -90
  identifier = "linkedin"
  url = "https://www.linkedin.com/company/5061707/"
[[languages.de.menu.secondary]]
  name = "Twitter"
  weight = -80
  identifier = "twitter"
  url = "https://twitter.com/port_zer0"





